[package]
name = "game"
version = "0.1.2"
authors = ["derezzedex <richardsoncusto@gmail.com>"]
edition = "2018"

[dev-dependencies]
criterion = "0.3"
num_cpus = "*"

[[bench]]
name = "chunk"
harness = false

[[bench]]
name = "terrain"
harness = false

[[bench]]
name = "terrain_multithread"
harness = false

[dependencies]
engine = { path = "../engine" }
cgmath = "0.18"
image = "0.25"
rayon = "1.10"
collision = { git = "https://github.com/rustgd/collision-rs" } # needed for `cgmath = 0.18`
specs = { version = "0.20", features = ["derive"] }
noise = "0.9"
uvth = "4.0"
dashmap = "6.1"
