[package]
name = "voxel_game"
version = "0.1.0"
authors = ["derezzedex"]
edition = "2018"

[dependencies]
glium = "0.22"
cgmath = "*"
image = "*"
rayon = "*"
specs = "*"
specs-derive = "*"
noise = "*"
uvth = "*"
dashmap = "3.4.3"
slice-deque = "*"
num_enum = "*"

[profile.release]
debug = true
