[package]
name = "voxel_game"
version = "0.1.0"
authors = ["derezzedex"]
edition = "2018"

[dependencies]
glium = "0.22"
cgmath = "*"
image = "*"
conrod = { version = "*", features = ["winit", "glium"] }
rayon = "*"
specs = "*"
specs-derive = "*"
noise = "*"

# [profile.release]
# opt-level = 'z'
# lto = true
# codegen-units = 1
