[package]
name = "voxel_game"
version = "0.1.2"
authors = ["derezzedex <richardsoncusto@gmail.com>"]
description = "Simple voxel game"
repository = "https://github.com/derezzedex/voxel_game"
license = "GPL-3.0"
edition = "2018"
readme = "README.md"

[dependencies]
glium = "0.22"
cgmath = "*"
collision = "0.20.1"
image = "^0.23.2"
rayon = "*"
specs = "*"
specs-derive = "*"
noise = "*"
uvth = "*"
dashmap = "*"
slice-deque = "*"
num_enum = "*"

[profile.release]
lto = true
